### ISSUE TITLE
"realpath: command not found" error when running all.sh

### ISSUE THREAD

**Issue by lyahdav** [react-community/jsc-android-buildscripts#20]
Following the installation instructions (not using Docker), I got to the step to run `all.sh` and got the following error:
```
➜  jsc-android-buildscripts git:(master) ✗  ./all.sh
=== compiling toolchain ===
=== compiling icu ===
./icu.sh: line 16: realpath: command not found
```

I'm on macOS Sierra 10.12.6.

**Comment by lyahdav** [comment]
If you have Homebrew you can fix this with `brew install coreutils`.

**Comment by hebertpalomino** [comment]
This fixed what I thought was a pods issue. 
```
resources.sh: line 7: realpath: command not found
:1581: error: Unexpected failure
```

Thanks!
