### ISSUE TITLE
How to determine JSC version at runtime 

### ISSUE THREAD

**Issue by bourquep** [react-community/jsc-android-buildscripts#29]
I have followed the steps in the readme to build my React Native Android app with the latest JSC, but am not noticing any performance improvements. 

How can I determine if my app is really using that JSC build and not the default, old one bundled with RN?

**Comment by newyankeecodeshop** [comment]
See if the `Proxy` object exists. It is not implemented by the JSC shipped with RN, but this more modern one has it.

**Comment by bourquep** [comment]
Thanks!

**Comment by K-Leon** [comment]
May you feedback if there are any upsides using this engine on Android performancewise during your tests?

**Comment by bourquep** [comment]
In my case, upgrading the JSC did not have any significant impact on Android performance. 

Pascal

**Comment by newyankeecodeshop** [comment]
That makes sense since the RN Babel settings convert most of the modern JS into ES5.
I'm also not sure how much JIT-compiling is going on with the newer runtime.

**Comment by DanielZlotin** [comment]
I think its a good idea to add some metadata file with version/build information, or some other way to expose that.

Performance should be noticeably better when compared to stock react-native (30% is a conservative figure I measured).. if it's not, you're probably didn't inject it correctly to the apk. One thing I would suggest to check is to use the apk explorer in android studio and check the size of the jsc.so inside the apk. This will be a good indication wether it's the stock version or the new one.

**Comment by bourquep** [comment]
@DanielZlotin Thanks for the tip. I have `x86/libjsc.so` at 2.8 MB and `armeabi-v7a/libjsc.so` at 2.2 MB. What can I infer from this?

**Comment by DanielZlotin** [comment]
@bourquep weird, that doesn't match any of the versions. Trying to reproduce myself encountered with a weird issue: the apk analyzer file size is vastly different than the actual .so file size. (for example apk analyze shows 2MB but when you unzip and check the file itself is 4.3Mb!)

**Comment by K-Leon** [comment]
I tried to check it with the availability of console.time. 

It's available in RN iOS. On Android it is one of the missing functions. I followed the installation instructions, but no success yet.... it's still missing. I guess this means, that the wrong jsc version is loaded.

**Comment by torkelrogstad** [comment]
By testing for the existence of `Symbol` or `Proxy`, what do you mean? I followed the instructions in the Readme, but the bug described in AirBNBs latest [RN post](https://medium.com/airbnb-engineering/react-native-at-airbnb-the-technology-dafd0b43838) still persists...

**Comment by newyankeecodeshop** [comment]
Those are globals like `Object` and `Function`. Execute `typeof Symbol` or `typeof Proxy`. If you are using the newer JavaScriptCore, the type will be "function". If you're using the RN built-in one, the type will be "undefined".

**Comment by torkelrogstad** [comment]
`typeof Proxy` and `typeof Symbol` both evaluate to `function`. However, I'm still having the issue where `Number.toLocalString` doesn't work, and just returns the number it was called on...

**Comment by newyankeecodeshop** [comment]
`Number.toLocaleString` requires the JSC build with the `Intl` library enabled. What is `typeof Intl`?
If it is not `object`, then you're missing the support for those APIs. You need to reference `jsc-android-intl` instead of `jsc-android` in your gradle. I can't remember the exact steps because we don't use that build. @DanielZlotin can point you in the right direction.

**Comment by torkelrogstad** [comment]
I just left the office, but I'll try that first thing in the morning. Thank you, this bug has troubled our team for weeks.

**Comment by bourquep** [comment]
@DanielZlotin Thanks, I've unzipped the APK and the sizes I'm observing don't match anything in that table...

I'm using r224109:

```
configurations.all {
    resolutionStrategy {
        force 'org.webkit:android-jsc:r224109'
    }
```

<img width="631" alt="image" src="https://user-images.githubusercontent.com/65096/41860265-3d29dbda-786c-11e8-8ecb-3cbb6aaaea20.png">

**Comment by DanielZlotin** [comment]
the size column in the [measure table](https://github.com/react-community/jsc-android-buildscripts/tree/master/measure#results) is the combined size of all compiled libs (in your case its `libjsc.so` + `libicudata_jsc.so` + `libicuuc_jsc.so)`

**Comment by DanielZlotin** [comment]
judging by your screenshot, it seems that you indeed have the correct `224109` version in the apk

**Comment by DanielZlotin** [comment]
Version info will be printed to logcat under tag "JavaScriptCore-Version" as soon as jsc is loaded
