### ISSUE TITLE
Adding updated JSC is 4mb more to apk, possible to remove the old JSC to save space?

### ISSUE THREAD

**Issue by thevolcanomanishere** [react-community/jsc-android-buildscripts#44]
### Issue Description
Maybe I have configured something wrong?

**Comment by DanielZlotin** [comment]
What do you mean by old jsc? The one that comes bundled with react-native? it is removed (overrided) by gradle.. The newer jsc is larger because the project itself grew a lot in 4 years.
If you want your apk smaller read [this](https://developer.android.com/studio/build/configure-apk-splits)
