### ISSUE TITLE
libc++_shared.so doubts 

### ISSUE THREAD

**Issue by abarra** [react-community/jsc-android-buildscripts#57]
Hey there! 

I'm using this for a non-react project and I dont get why in the dist folder there is the libc++_shared.so library. I believe this is from ndk and i don't need to put this file in my project.

**Comment by DanielZlotin** [comment]
[libc++_shared](https://developer.android.com/ndk/guides/cpp-support) is the STL used by JavaScriptCore (or any other library that `#include` anything from the C++ standard) and it's linked in runtime. It would be a surprise to me if you removed the STL and things still worked. Does it?
