### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by skoshy** [react-community/jsc-android-buildscripts#58]
### Issue Description

Is this supported on Windows? When trying to `npm i --save jsc-android`, I get an error concerning fsevents, which is only available on macOS.

- "jsc-android": "224109.1.0",
- "react-native": "0.57.0"

**Comment by skoshy** [comment]
Never mind! I followed the instructions and put "jsc-android" with the given version in the readme into the dependencies and then ran `npm install` and everything worked. Strange that works instead of just using `npm install --save jsc-android`, but just glad it works now!

**Comment by pstanton** [comment]
but just adding the dependency doesn't mean jsc is updated ??
